// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6RUa8Qz13lr0gDvPzoqueAmjEOKis8NE',
    appId: '1:1096698039231:web:8565839cea8648adf62f0a',
    messagingSenderId: '1096698039231',
    projectId: 'ingoralajagani-70f57',
    authDomain: 'ingoralajagani-70f57.firebaseapp.com',
    databaseURL: 'https://ingoralajagani-70f57-default-rtdb.firebaseio.com',
    storageBucket: 'ingoralajagani-70f57.appspot.com',
    measurementId: 'G-J44MQZ442X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGLepbXQZd-IuPzoxqYlMkbbfguKNzRw',
    appId: '1:1096698039231:android:dbfc3510d1274445f62f0a',
    messagingSenderId: '1096698039231',
    projectId: 'ingoralajagani-70f57',
    databaseURL: 'https://ingoralajagani-70f57-default-rtdb.firebaseio.com',
    storageBucket: 'ingoralajagani-70f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARRRwSqpXy_xdHQ028HVrs5JYIgDqJL3I',
    appId: '1:1096698039231:ios:5ba8386b8abac663f62f0a',
    messagingSenderId: '1096698039231',
    projectId: 'ingoralajagani-70f57',
    databaseURL: 'https://ingoralajagani-70f57-default-rtdb.firebaseio.com',
    storageBucket: 'ingoralajagani-70f57.appspot.com',
    androidClientId: '1096698039231-16h806o8cgmtn6e2msple75k1di04aos.apps.googleusercontent.com',
    iosClientId: '1096698039231-f5va3r50l548fp9ofe7tg1lgsmdhl3h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingorala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARRRwSqpXy_xdHQ028HVrs5JYIgDqJL3I',
    appId: '1:1096698039231:ios:5ba8386b8abac663f62f0a',
    messagingSenderId: '1096698039231',
    projectId: 'ingoralajagani-70f57',
    databaseURL: 'https://ingoralajagani-70f57-default-rtdb.firebaseio.com',
    storageBucket: 'ingoralajagani-70f57.appspot.com',
    androidClientId: '1096698039231-16h806o8cgmtn6e2msple75k1di04aos.apps.googleusercontent.com',
    iosClientId: '1096698039231-f5va3r50l548fp9ofe7tg1lgsmdhl3h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingorala',
  );
}
